# Building plans
# Sans
[buildPlans.lcg-code]
family = "Maki-e LCG Code"
design = ["shape-straight-bar"]

[buildPlans.lcg-code.post]
design = ['wd-makie']

[buildPlans.lcg-term]
family = "Maki-e LCG Term"
design = ["shape-straight-bar", "term"]

[buildPlans.lcg-term.post]
design = ['wd-makie']

[buildPlans.lcg-type]
family = "Maki-e LCG Type"
design = ["shape-straight-bar", "type"]

[buildPlans.lcg-type.post]
design = ['wd-makie']

# Slab
[buildPlans.lcg-codeslab]
family = "Maki-e LCG Code Slab"
design = ["shape-straight-bar", "slab"]

[buildPlans.lcg-codeslab.post]
design = ['wd-makie']

[buildPlans.lcg-termslab]
family = "Maki-e LCG Term Slab"
design = ["shape-straight-bar", "term", "slab"]

[buildPlans.lcg-termslab.post]
design = ['wd-makie']

[buildPlans.lcg-typeslab]
family = "Maki-e LCG Type Slab"
design = ["shape-straight-bar", "type", "slab"]

[buildPlans.lcg-typeslab.post]
design = ['wd-makie']

# Export plans
# This mapping affects the process of creating ZIP archives only
[exportPlans]
01-lcg-code = "lcg-code"
02-lcg-term = "lcg-term"
03-lcg-codeslab = "lcg-codeslab"
04-lcg-termslab = "lcg-termslab"

# Weight mappings (style => shape weight, CSS weight)
#   Shape weight : affects the shape of the glyphs
#   CSS weight   : affects the font menu name and webfont CSS
# [weights.thin]
# shape = 100
# menu  = 100
# css   = 100

# [weights.extralight]
# shape = 200
# menu  = 200
# css   = 200

# [weights.light]
# shape = 300
# menu  = 300
# css   = 300

[weights.regular]
shape = 400
menu  = 400
css   = 400

# [weights.medium]
# shape = 500
# menu  = 500
# css   = 500

# [weights.semibold]
# shape = 600
# menu  = 600
# css   = 600

[weights.bold]
shape = 700
menu  = 700
css   = 700

# [weights.extrabold]
# shape = 800
# menu  = 800
# css   = 800

# [weights.heavy]
# shape = 900
# menu  = 900
# css   = 900

# Slant mappings (style => CSS)
# NOTE: This mapping does NOT affect the font's metadata, only affects
#       the webfont CSS. Change `parameters.toml` instead.
[slants]
upright = "normal"
# oblique = "oblique"
italic = "italic"
