# Building plans
# Sans
[buildPlans.lcg-sans-code]
family = "Maki-e Sans Code LCG"
design = ["shape-straight-bar"]

[buildPlans.lcg-sans-code.post]
design = ['wd-makie']

[buildPlans.lcg-sans-konqi]
family = "Maki-e Sans Konqi LCG"
design = ["shape-straight-bar", "termlig"]

[buildPlans.lcg-sans-konqi.post]
design = ['wd-makie']

[buildPlans.lcg-sans-type]
family = "Maki-e Sans Type LCG"
design = ["shape-straight-bar", "type"]

[buildPlans.lcg-sans-type.post]
design = ['wd-makie']

[buildPlans.lcg-sans-cc]
family = "Maki-e Sans CC LCG"
design = ["shape-straight-bar", "cc"]

[buildPlans.lcg-sans-cc.post]
design = ['wd-makie']

[buildPlans.lcg-sans-mono]
family = "Maki-e Sans Mono LCG"
design = ["shape-straight-bar", "no-ligation"]

[buildPlans.lcg-sans-mono.post]
design = ['wd-makie']

[buildPlans.lcg-sans-term]
family = "Maki-e Sans Term LCG"
design = ["shape-straight-bar", "term"]

[buildPlans.lcg-sans-term.post]
design = ['wd-makie']

# Slab
[buildPlans.lcg-slab-code]
family = "Maki-e Slab Code LCG"
design = ["slab"]

[buildPlans.lcg-slab-code.post]
design = ['wd-makie']

[buildPlans.lcg-slab-konqi]
family = "Maki-e Slab Konqi LCG"
design = ["termlig", "slab"]

[buildPlans.lcg-slab-konqi.post]
design = ['wd-makie']

[buildPlans.lcg-slab-type]
family = "Maki-e Slab Type LCG"
design = ["type", "slab"]

[buildPlans.lcg-slab-type.post]
design = ['wd-makie']

[buildPlans.lcg-slab-cc]
family = "Maki-e Slab CC LCG"
design = ["cc", "slab"]

[buildPlans.lcg-slab-cc.post]
design = ['wd-makie']

[buildPlans.lcg-slab-mono]
family = "Maki-e Slab Mono LCG"
design = ["no-ligation", "slab"]

[buildPlans.lcg-slab-mono.post]
design = ['wd-makie']

[buildPlans.lcg-slab-term]
family = "Maki-e Slab Term LCG"
design = ["term", "slab"]

[buildPlans.lcg-slab-term.post]
design = ['wd-makie']

# Export plans
# This mapping affects the process of creating ZIP archives only
[exportPlans]
01-lcg-sans-code = "lcg-sans-code"
02-lcg-sans-konqi = "lcg-sans-konqi"
03-lcg-sans-type = "lcg-sans-type"
04-lcg-sans-cc = "lcg-sans-cc"
05-lcg-sans-mono = "lcg-sans-mono"
06-lcg-sans-term = "lcg-sans-term"
07-lcg-slab-code = "lcg-slab-code"
08-lcg-slab-konqi = "lcg-slab-konqi"
09-lcg-slab-type = "lcg-slab-type"
10-lcg-slab-cc = "lcg-slab-cc"
11-lcg-slab-mono = "lcg-slab-mono"
12-lcg-slab-term = "lcg-slab-term"

# Weight mappings (style => shape weight, CSS weight)
#   Shape weight : affects the shape of the glyphs
#   CSS weight   : affects the font menu name and webfont CSS

[weights.extralight]
shape = 200
menu  = 200
css   = 200

[weights.light]
shape = 300
menu  = 300
css   = 300

[weights.normal]
shape = 350
menu  = 350
css   = 350

[weights.regular]
shape = 400
menu  = 400
css   = 400

[weights.medium]
shape = 500
menu  = 500
css   = 500

[weights.bold]
shape = 700
menu  = 700
css   = 700

[weights.heavy]
shape = 900
menu  = 900
css   = 900

# Slant mappings (style => CSS)
# NOTE: This mapping does NOT affect the font's metadata, only affects
#       the webfont CSS. Change `parameters.toml` instead.
[slants]
upright = "normal"
# oblique = "oblique"
italic = "italic"
